### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by AndnixSH** [Feisar2097/SplitApkMerger#2]
Got this error when trying to merge. I'm using Python 3.10.2
```
SplitMerger: Working on D:\Apk
Traceback (most recent call last):
  File "D:\splitmerger.py", line 197, in <module>
    for key, splits in files.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

This is the file structure
![image](https://user-images.githubusercontent.com/40742924/167267558-eae01c06-43f7-4303-8d62-e0c155d85416.png)

**Comment by Feisar2097** [comment]
After decompilation, there should be folders with similar names. 
Where base is the main apk and split_config.* are additional splits

![Files](https://user-images.githubusercontent.com/38229067/168493568-41ebf589-fa19-4c22-8073-bf8f21393fbc.png)

In your case, the first folder needs to be renamed "base", and the rest need to add "split_" at the beginning of the name.

**Comment by AndnixSH** [comment]
It's annoying to rename manually.

I have found better source that is more automatic
